### ISSUE TITLE
Missing CSS background for tarteaucitronSave div

### ISSUE THREAD

**Issue by mably** [AmauriC/tarteaucitron.js#1210]
The background is transparent as no CSS background seems to be specified:

<img width="1061" alt="image" src="https://github.com/AmauriC/tarteaucitron.js/assets/385653/9817e3c4-fd0f-4225-af61-09fd6bf065dc">

We could add something like this to the default CSS to fix the problem:

```css
#tarteaucitron #tarteaucitronSave {
  background: #333;
}
```
