### ISSUE TITLE
Twitter Bootstrap compliant

### ISSUE THREAD

**Issue by olddevyg** [AmauriC/tarteaucitron.js#8]
I suggest you add an option (or force) to make the css more "Bootstrap compliant" as many of websites use the framework as a base for theming (many of ours do). I mean only for the media queries which are completly differents from yours.
My suggestion :

``` css
@media screen and (max-width:479px) {
    #tarteaucitron #tarteaucitronInfo {
        font-size: 16px !important;
        background-image: none;
        padding-right: 0;
        text-align: center;
    }

    #tarteaucitron .tarteaucitronLine .tarteaucitronName {
        width: 90% !important;
    }

    #tarteaucitron .tarteaucitronLine .tarteaucitronAsk {
        float: left !important;
        margin: 10px 15px 5px;
    }
}

@media screen and (max-width:767px) {
    #tarteaucitron {
        border: 0 !important;
        bottom: 0 !important;
        height: 100% !important;
        max-height: 100% !important;
        max-width: 100% !important;
        top: 0 !important;
        width: 100% !important;
    }

    #tarteaucitron #tarteaucitronClosePanel {
        display: block !important;
    }
}

@media screen and (min-width:768px) and (max-width:991px) {
    #tarteaucitron {
        max-height: 100% !important;
        max-width: 100% !important;
        width: 90% !important;
        margin: 0 5%;
    }
}
```
